attributes:
  BuildIndependentTargetsInParallel: '1'
  LastSwiftUpdateCheck: '1330'
  LastUpgradeCheck: '1330'
configs:
  Debug: debug
  Release: release
name: MuscleRecord
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++17
      IPHONEOS_DEPLOYMENT_TARGET: '15.0'
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++17
      IPHONEOS_DEPLOYMENT_TARGET: '15.0'
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  MuscleRecord:
    dependencies:
    - package: Firebase
      product: FirebaseAuth
    - package: Firebase
      product: FirebaseFirestore
    - sdk: StoreKit.framework
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: AppIcon2 AppIcon1
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: 'YES'
          CODE_SIGN_ENTITLEMENTS: MuscleRecord/MuscleRecord.entitlements
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"MuscleRecord/Preview Content"'
          DEVELOPMENT_TEAM: 4WXTDSDQPZ
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: MuscleRecord/Info.plist
          INFOPLIST_KEY_CFBundleDisplayName: "\u7B4B\u30C8\u30EC\u8A18\u9332"
          INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIStatusBarHidden: 'NO'
          INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
          MARKETING_VERSION: '2.4'
          PRODUCT_BUNDLE_IDENTIFIER: com.yazujumusa.muscle-record
          PRODUCT_NAME: Muscle Record
          SUPPORTS_MACCATALYST: 'NO'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '1'
        Release:
          ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: AppIcon2 AppIcon1
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: 'YES'
          CODE_SIGN_ENTITLEMENTS: MuscleRecord/MuscleRecord.entitlements
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"MuscleRecord/Preview Content"'
          DEVELOPMENT_TEAM: 4WXTDSDQPZ
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: MuscleRecord/Info.plist
          INFOPLIST_KEY_CFBundleDisplayName: "\u7B4B\u30C8\u30EC\u8A18\u9332"
          INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIStatusBarHidden: 'NO'
          INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
          MARKETING_VERSION: '2.4'
          PRODUCT_BUNDLE_IDENTIFIER: com.yazujumusa.muscle-record
          PRODUCT_NAME: Muscle Record
          SUPPORTS_MACCATALYST: 'NO'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '1'
    sources:
    - path: GoogleService-Info.plist
    - path: MuscleRecord/Assets.xcassets
    - path: MuscleRecord/LaunchScreen.storyboard
    - name: Model
      path: MuscleRecord/Model
    - path: MuscleRecord/MuscleRecordApp.swift
    - name: Preview Content
      path: MuscleRecord/Preview Content
    - name: View
      path: MuscleRecord/View
    - name: ViewModel
      path: MuscleRecord/ViewModel
    type: application
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.16.0
