default_platform(:ios)

platform :ios do
  desc "Build and Archive the App"
  lane :archive do
    match(
	type: "appstore",
	app_identifier: "com.yazujumusa.muscle-record",
	git_url: "https://github.com/Mucchoo/MuscleRecord-Fastlane.git"
    )

    gym(
      project: "MuscleRecord.xcodeproj",
      scheme: "MuscleRecord",
      clean: true,
      silent: false,
      output_directory: "./build",
      output_name: "MuscleRecord",
      export_options: {
        signingStyle: "automatic",
        method: "app-store",
        allowProvisioningUpdates: true
      }
    )
  end

  desc "Deploy to DeployGate"
  lane :deploy_to_deploygate do
    deploygate(
      api_token: ENV["DEPLOY_GATE_API_KEY"],
      user: "musamusclerecord",
      ipa: "./build/MuscleRecord.ipa"
    )
  end
end