on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: macos-13
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Git credentials
      run: |
        git config --global user.name "Mucchoo"
        git config --global user.email "yazujumusa@gmail.com"

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.0'

    - name: Setup Ruby and Cache Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Unlock macOS keychain
      run: |
        security default-keychain -s login.keychain
        security unlock-keychain -p "" login.keychain

    - name: Build and Archive App & Deploy to DeployGate
      run: |
        bundle exec fastlane archive
        bundle exec fastlane deploy_to_deploygate
      env:
        DEPLOY_GATE_API_KEY: ${{ secrets.DEPLOY_GATE_API_KEY }}
        MATCH_AUTH_TOKEN: ${{ secrets.MATCH_AUTH_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
